### ISSUE TITLE
How to make my own dataset only by images not by videos

### ISSUE THREAD

**Issue by 123zhouzhou** [JihyongOh/JSI-GAN#7]
I want to use my own dataset for training and testing the code, so I want to know if I can make .mat file(Input and GT) only by my own RGB images not frames from videos. 
Thank you~

**Comment by sooyekim** [comment]
Hi @123zhouzhou ,

Thanks for the interest in our work!

As for your question, of course! 
You could create a .mat file using the save function in MATLAB, which can be used as:
`save('your_data.mat','your_data','-v7.3')` (don't forget to insert the -v7.3 flag!)

This .mat file should be of size HxWxCxN (eg. 120x120x3x10000, for example, if you create 10000 training patches of 120x120 size with RGB channels). You could create a .mat file for the SDR training patches, and a corresponding .mat file for the HDR training patches just as we did. 

You could train the network with your .mat file by designating the arguments, --train_data_path_LR_SDR and --train_data_path_HR_HDR .

Please LMK if you have any other questions!

Thanks,
Soo Ye

**Comment by 8bignic8** [comment]
Hey 
is there any other way to create a file to feed into the JSI-Gan, for exemple with python or a clone of matlab in python?

greetings

**Comment by sooyekim** [comment]
Hi @8bignic8 ,
You could use the h5py library to save .mat files with python, something like [this](https://stackoverflow.com/questions/36362831/creating-a-mat-file-of-v7-3-in-python).
Thanks!

**Comment by 8bignic8** [comment]
> Hi @8bignic8 ,
> You could use the h5py library to save .mat files with python, something like [this](https://stackoverflow.com/questions/36362831/creating-a-mat-file-of-v7-3-in-python).
> Thanks!

How do I need to save my generated HDR matrix into the .mat file, 

e.g. 
HDR Pictures Read: 
[[[0.00247192 0.00375366 0.00424194]
  [0.00247192 0.00375366 0.00424194]
  [0.00247192 0.00375366 0.00424194]
How many steps do I need to shift the dezimalpoint to the right?
 
should it look like: 
[[[0.247192 0.375366 0.424194]
or
[[[247.192 375.366 424.194]

Is the format 'uint8' for SDR .mat file and uint16 for HDR .mat file correct?
I´m sorry for that many questions but I´m writng a python script where one can generate Train and or test .mat files for your mashine for my bachelor thesis. It is going live on my github as soon as it works ;D

Tanks Nico :)

**Comment by sooyekim** [comment]
@8bignic8 
Hi Nico,
That's great!

You might already know from reading our paper, but our HDR setting is a bit different to other papers since we handle HDR10 format commercial videos (10-bit/pixel, PQ-OETF, BT.2020).
For our experiments, we used 10-bit YUV HDR frames (integer values between 0 and 1023), and divided by 1023 in our code to normalize the input to [0, 1] in [read_mat_file()](https://github.com/JihyongOh/JSI-GAN/blob/b636463385fb693effe43cecc28867f4308e3e20/utils.py#L32) in utils.py.

- I'm not sure what the dynamic range is for your HDR data but you could modify [read_mat_file()](https://github.com/JihyongOh/JSI-GAN/blob/b636463385fb693effe43cecc28867f4308e3e20/utils.py#L32) so that the SDR-HDR train patch pairs are both between [0, 1] (eg. if the HDR patch is 16 bits, you could divide the input by 2^16-1). Or, you could provide SDR frames in range [0, 255] (integer) and HDR frames in range [0, 1023] (integer) to not modify the read_mat_file() function. The important thing here, is that the network should be trained with patches normalized to the range [0, 1]. 
- As mentioned above, YUV frames were given in our setting (8 bit YUV for SDR frames, and 10 bit YUV for HDR frames). This was a simple operation in our case, because we started from commercial .mp4 10-bit HDR videos, which can easily be converted to .yuv using ffmpeg. However, if you wish to train & test on RGB, I guess that's also okay. JSI-GAN doesn't explicitly convert RGB to YUV or YUV to RGB. 
-  'uint8' for SDR .mat file and 'uint16' for HDR .mat file is correct because SDR .mat file contains [0, 255] integer values, and HDR .mat file contains [0, 1023] integer values.

LMK if you have any other questions!
Soo Ye

**Comment by sooyekim** [comment]
Hi Nico,
By normalizing to the range [0, 1], I just meant dividing by the maximum value (255 or 1023), which is common practice in DL for low level vision. You shouldn't be converting to [0, 1] using min values of each image because the pixel value signifies an absolute brightness value. Just dividing by the absolute maximum (255, 1023, 2^16-1, etc) is enough.

As I mentioned earlier, if your test scenario also uses RGB images, you can just retrain our network with your RGB images (after just dividing by 255, 1023, etc depending on the dynamic range). So training on LR_SDR RGB and HR_HDR RGB pairs, and also testing on LR_SDR RGB and HR_HDR RGB.

If you still wish to convert to YUV, it's a bit complicated. I recommend you take a look at Fig. 2 in my other paper, [Deep SR-ITM](https://arxiv.org/ftp/arxiv/papers/1904/1904.11176.pdf).
* For SDR images, you can divide by 255 then convert to YUV (rgb2ycbcr function in Matlab).
* For HDR images, if your .hdr files are raw luminance values and in RGB 709 (BT.709), you have to convert to RGB 2020, apply PQ-OETF, then convert to YUV using the conversion matrices for BT.2020. If you don't wish to generate images in RGB 2020, no need to convert to RGB 2020. You could directly apply PQ-OETF and convert to YUV using conversion matrices for BT.709.

For the conversions, details including conversion matrices are in the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG. Some code in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/19) might also be useful.
However due to the complex conversion pipelines, I do strongly recommend re-training with RGB pairs (as you're looking to train the model anyway and use .hdr images not .yuv videos).

Thanks!
Soo Ye
