### ISSUE TITLE
Padding output shape is different from the mentioned comments in the code

### ISSUE THREAD

**Issue by sujeet-gandhi** [JihyongOh/JSI-GAN#9]
Hi @sooyekim ,
Thanks for the great work.
I am running inference on `test.mat` files with scaling factor `4`.
According to the comments on this line of the code: https://github.com/JihyongOh/JSI-GAN/blob/master/ops.py#L249
If i/p size is (1,100,170,3) then the output should be (1,120,190,3) as value of pad is 20 (41//2), but when i am running the code on my machine i am getting the output shape as (1.140,170,3). Is this behavior desirable?
Below i have attached the PDB log for your reference:

> img_pad = tf.pad(x, tf.constant([[0, 0], [pad, pad], [0, 0], [0, 0]]))  # [B, H+pad, W+pad, C]
(Pdb) x.shape
TensorShape([Dimension(1), Dimension(100), Dimension(170), Dimension(3)])
(Pdb) img_pad.shape
TensorShape([Dimension(1), Dimension(140), Dimension(170), Dimension(3)])

**Comment by sooyekim** [comment]
Hi @sujeet-gandhi ,

Thanks for your interest in our work!

Sorry for the confusing comment. The output shape you got is correct, and the comment should be changed to [B, H+2*pad, W, C]. This is because vertical filters are applied first.
The width direction is padded in [line 258](https://github.com/JihyongOh/JSI-GAN/blob/master/ops.py#L258) before the horizontal filters are applied.

LMK if you have any other questions!
Soo Ye

**Comment by sooyekim** [comment]
Clarified this in the comments on line 249 and 258.
Thanks!

**Comment by sujeet-gandhi** [comment]
Thanks much, for the clarification.
